.catalog:
  name: Network Services
  version: v0.0.2
  minimum_rancher_version: v1.1.99
  maximum_rancher_version: v1.3.99
  questions:
    - variable: "DOCKER_BRIDGE"
      label: "Docker Bridge"
      description: "Name of Docker Bridge. Default is `docker0`"
      type: "string"
      default: "docker0"
      required: true
