---
version: "2"
services:
  calibre-web:
    image: linuxserver/calibre-web

    ports:
      - ${http_port}:8083

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"

    restart: unless-stopped
