---
version: "2"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    ports:
      - ${http_port}:3579
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/appdata/ombi/config:/config
    restart: unless-stopped
