  ombi:
    image: linuxserver/ombi
    container_name: ombi

    ports:
      - ${http_port}:3579

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"

    volumes:
     - /home/ombi:/config

    restart: unless-stopped
