version: '2'
catalog:
  name: "ombi"
  version: "v3.0.5202-ls68"
  description: "Want a Movie or TV Show on Plex or Emby? Use Ombi!"
  uuid: ombi-0
  minimum_rancher_version: v0.56.0
  questions:
    - variable: http_port
      description: "Public HTTP port to access ombi's webui."
      label: "HTTP Port"
      required: true
      default: "3000"
      type: "int"
    - variable: "volume_driver"
      description: "Volume driver to associate with this service."
      label: "Volume Driver"
      required: true
      default: "local"
      type: enum
      options: # List of options if using type of `enum`
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
services:
  ombi:
    scale: 1
    retain_ip: true
    health_check:
      port: 4012
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
