---
version: "2"
services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
      - CONTEXT_PATH=whitehome.io #optional

    volumes:
      - /home/airsonic:/config
      - /media/nova/media/Audio:/music
      - </path/to/playlists>:/playlists
      - </path/to/podcasts>:/podcasts

    ports:
      - 4040:4040

    restart: unless-stopped
