version: '2'
services:
  network-policy-manager:
    privileged: true
    network_mode: host
    pid: host
    image: rancher/network-policy-manager:v0.1.0
    labels:
      io.rancher.scheduler.global: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
