.catalog:
    name: "Rancer Secrets"
    version: v0.0.1
    description: "Volume plugin to fetch and present secrets through files on tmpfs"
    minimum_rancher_version: v1.4.0-rc3
    maximum_rancher_version: v1.4.99
secrets-driver:
  storage_driver:
    name: rancher-secrets
    description: "A tmpfs driver for secrets"
    scope: local
    create_supported: false
    volume_access_mode: singleHostRW
    volume_capabilities:
      - secrets
    start_on_create: true
