version: "2"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4003:4533
    user: 99:100
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info
      ND_BASEURL: ""
    volumes:
      - /home/appdata/lidarr:/data
      - /media/nova/media/Audio/Collection:/music:ro
    restart: unless-stopped
