.catalog:
    name: Network Services for Windows
    version: v0.1.0
    minimum_rancher_version: v1.6.13-rc1
    maximum_rancher_version: v1.6.14
    questions:
    - variable: DNS_RECURSER_TIMEOUT
      label: Timeout for Rancher DNS Recurser
      description: Specify timeout in seconds for DNS Recurser.
      required: true
      default: 2
      type: int
    - variable: TTL
      label: TTL for service discovery answers
      description: How long answers for *.rancher.internal responses are valid
      required: true
      default: 1
      type: int
