.catalog:
  name: "ECR Credential Updater"
  version: "v3.0.0"
  description: "Updates credentials for ECR in Rancher"
  minimum_rancher_version: "v1.6.15-rc1"
  questions:
    - variable: "aws_access_key_id"
      label: "AWS Access Key ID"
      description: "AWS API Access Key to use for obtaining ECR credentials. Not required if using IAM roles."
      required: false
      type: "string"
    - variable: "aws_secret_access_key"
      label: "AWS Secret Access Key"
      description: "AWS API Secret Key to use for obtaining ECR credentials. Not required if using IAM roles."
      required: false
      type: "string"
    - variable: "aws_region"
      label: "AWS Region"
      description: "AWS Region that hosts the ECR"
      default: us-east-1
      required: true
      type: "string"
    - variable: "auto_create"
      label: "Auto Create"
      description: "Automatically create registry in Rancher for corresponding ECR repo if it doesn't already exist"
      default: "false"
      required: true
      type: "string"
    - variable: "log_level"
      label: "Log Level"
      description: "Logging level to run service at"
      default: "INFO"
      required: true
      type: "string"
    - variable: "registry_in_which_environment"
      type: enum
      label: "Registry Environment"
      description: "Which environment is the AWS registry located?"
      default: current
      options:
        - current
        - other
    - variable: "environment_api_endpoint"
      label: "URL (Environment API Endpoint) of Registry to be Updated"
      description: "URL for where the registry is located. This is the endpoint, which can be found under the Advanced Options under API -> Keys, for an Environment API Key."
      default: ""
      required: false
      type: "string"
    - variable: "environment_api_access_key"
      label: "Access Key of an Environment API Key"
      description: "This access key must be for the environment where the registry will need to be updated. This access key will be created in the same environment listed for the URL. This can be created in the Advanced Options under API."
      default: ""
      required: false
      type: "string"
    - variable: "environment_api_secret_key"
      label: "Secret Key of an Environment API Key"
      description: "This secret key must be for the environment where the registry will need to be updated. This secret key will be created in the same environment listed for the URL. This can be created in the Advanced Options under API."
      default: ""
      required: false
      type: "string"
ecr-updater:
  scale: 1
