---
version: "2"
services:
  wikijs:
    image: linuxserver/wikijs
    container_name: wikijs
    ports:
      - 4010:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/appdata/wikijs:/config
      - /home/appdata/wikijs/data:/data
    restart: unless-stopped
