.catalog:
    name: Scheduler
    description: A resource based scheduler plugin for Rancher.
    version: v0.2.0
    minimum_rancher_version: v1.1.99
    maximum_rancher_version: v1.1.99
scheduler:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
