---
version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr

    ports:
      - ${http_port}:4848

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"

    volumes:
      - /home/radarr:/config
      - /media/nova/media/Video/Movies:/movies
      - /media/nova/contentgateway/process/Video/Movies:/downloads

    restart: unless-stopped
