---
  heimdall:
    image: linuxserver/heimdall

    ports:
      - ${http_port}:80
      - ${https_port}:443

    security_opt:
      - no-new-privileges:true

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
      
    restart: unless-stopped
