---
version: "2"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - 4021:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"
    volumes:
      - /home/appdata/heimdall:/config
    restart: unless-stopped
