.catalog:
    name: Scheduler
    description: A resource based scheduler plugin for Rancher.
    version: v0.4.0
    minimum_rancher_version: v1.4.0-rc1
    maximum_rancher_version: v1.4.99
    questions:
        - variable: "RANCHER_DEBUG"
          label: "Enable Debug Logs"
          description: "This will enable very verbose debug logs."
          type: "boolean"
          default: "false"
          required: true

scheduler:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
