---
version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett

    ports:
      - ${http_port}:9117

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"

    volumes:
      - /home/jackett:/config

    restart: unless-stopped
