.catalog:
  name: "Rancher IPsec"
  version: "0.1.1"
  minimum_rancher_version: v1.6.3-rc1
  maximum_rancher_version: v1.6.5
  questions:
    - variable: "DOCKER_BRIDGE"
      label: "Docker Bridge"
      description: "Name of Docker Bridge. Default is `docker0`"
      type: "string"
      default: "docker0"
      required: true
    - variable: MTU
      label: "MTU for the network"
      description: "Adjust the MTU for the network, according to your needs. Ex: GCE(1460), AWS(1500), etc"
      required: true
      default: 1500
      type: int
    - variable: "SUBNET"
      label: "Subnet"
      description: "The subnet to use for the managed IPSEC network."
      type: "string"
      default: '10.42.0.0/16'
      required: true
    - variable: "RANCHER_DEBUG"
      label: "Enable Debug Logs"
      description: "This will enable very verbose debug logs."
      type: "boolean"
      default: "false"
      required: true
    - variable: "RANCHER_HAIRPIN_MODE"
      label: "Enable Hairpin mode"
      description: "If this is enabled, Promiscuous mode needs to be disabled."
      type: "boolean"
      default: "false"
      required: true
    - variable: "RANCHER_PROMISCUOUS_MODE"
      label: "Enable Promiscuous mode on the bridge"
      description: "If this is enabled, Hairpin mode needs to be disabled."
      type: "boolean"
      default: "true"
      required: true
    - variable: "HOST_PORTS"
      label: "Enable Host Ports"
      description: "Flag to enable/disable publishing the ports on the hosts"
      type: "boolean"
      default: "true"
      required: true
