name: Swarm
description: Default Swarm template
stacks:
  - name: portainer
    templateId: 'community:infra*portainer'
  - name: swarm
    templateId: 'community:infra*swarm'
  - name: network-services
    templateId: 'library:infra*network-services'
  - name: ipsec
    templateId: 'library:infra*ipsec'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
