version: '2'
services:
  container-crontab:
    image: rancher/container-crontab:v0.2.0
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.scheduler.global: true
      io.rancher.container.hostname_override: container_name
