version: '2'
.catalog:
  name: "Windows (Experimental)"
  version: "v0.0.1"
  description: Experimental support for running Windows containers on Rancher
  minimum_rancher_version: "v1.3.0-rc1"
  questions:
    - variable: "TRANSPARENT_NETWORK_DRIVER_NAME"
      label: "Name of Transparent Network Driver"
      type: "string"
      required: true
      default: "transparent"
      description: This is the name of the transparent network driver on your host.

services:
    nat:
      network_driver:
        name: NAT Networking
        default_network:
          name: nat
          kind: nat

    transparent:
      network_driver:
        name: Transparent Networking
        default_network:
          name: transparent
          kind: $TRANSPARENT_NETWORK_DRIVER_NAME
