version: '2'
catalog:
  name: "hydra2"
  version: "v2.19.6-ls69"
  description: "Usenet meta search"
  uuid: hydra2-0
  minimum_rancher_version: v0.56.0
  questions:
    - variable: "volume_driver"
      description: "Volume driver to associate with this service."
      label: "Volume Driver"
      required: true
      default: "local"
      type: enum
      options: # List of options if using type of `enum`
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
services:
  hydra2:
    scale: 1
    retain_ip: true
    health_check:
      port: 5076
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
