---
version: "2"
services:
  caddy:
    image: caddy:<version>

    ports:
      - ${http_port}:80
      - ${https_port}:443

    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/New_York"

    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
      
      restart: unless-stopped
