name: Network Policy Manager
description: |
  Manager that applies Rancher network policies.
version: v0.0.4
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
